version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: pguser
      POSTGRES_DB: udiadb
  testdb:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: pguser
      POSTGRES_DB: udiadbtest
  # test:
  #   build: .
  #   depends_on:
  #     - testdb
  #     - redis
  #   links:
  #     - testdb:testdb
  #     - redis:redis
  #   command: sh -c "sleep 5 && yarn test"
  #   environment:
  #     NODE_ENV: test
  #     PORT: 3000
  #     REDIS_URL: redis://redis:6379
  #     TYPEORM_TYPE: postgres
  #     SQL_TEST_DB: udiadbtest
  #     SQL_HOST: testdb
  #     SQL_USER: pguser
  #     SQL_PASSWORD: mysecretpassword
  #     SQL_TEST_PORT: 5432
