version: '3'

networks:
  roachnet:

services:
  roach:
    image: cockroachdb/cockroach
    command: start --insecure
    ports:
      - 8080:8080
      - 26257:26257
    networks:
        - roachnet
    volumes:
      - ./data/roach:/cockroach/cockroach-data
  roach-a:
    image: cockroachdb/cockroach
    command: start --insecure --join=roach
    networks:
        - roachnet
    volumes:
      - ./data/roach-a:/cockroach/cockroach-data
  roach-b:
    image: cockroachdb/cockroach
    command: start --insecure --join=roach
    networks:
        - roachnet
    volumes:
      - ./data/roach-b:/cockroach/cockroach-data
  roach-c:
    image: cockroachdb/cockroach
    command: start --insecure --join=roach
    networks:
        - roachnet
    volumes:
      - ./data/roach-c:/cockroach/cockroach-data

#     TYPEORM_TYPE: postgres
#     SQL_DB: udiadb
#     SQL_HOST: localhost
#     SQL_USER: root
#     SQL_PASSWORD: 
#     SQL_PORT: 26257
