class User {
  /** The email of the user. */
  public email: string;
  /**
   * The password for this user.
   * Passwords must be manipulated before being sent to the server.
   */
  public password: string;
  /** The number of iterations to use for KDF. */
  public pwCost: string;
  /** Generated by the client during registration. */
  public pwSalt: string;

  constructor(email: string, password: string, pwCost: string, pwSalt: string) {
    this.email = email;
    this.password = password;
    this.pwCost = pwCost;
    this.pwSalt = pwSalt;
  }
}
